# Generated by Django 4.0.6 on 2023-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spenging_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='сумма затрат'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='баланс'),
        ),
    ]
