# Generated by Django 4.0.6 on 2023-05-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='фамилия')),
                ('birth', models.IntegerField(verbose_name='год рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('isbn', models.CharField(max_length=100)),
                ('release', models.IntegerField(verbose_name='год выпуска')),
                ('pages', models.IntegerField(verbose_name='количество страниц')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_library.autor', verbose_name='автор')),
            ],
        ),
    ]
