# Generated by Django 4.0.6 on 2023-05-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='тип помещения')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'тип помещения',
                'verbose_name_plural': 'типы помещений',
            },
        ),
        migrations.CreateModel(
            name='SaleHouseNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='создано')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(null=True, verbose_name='дата публикации')),
                ('description', models.TextField(default='', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='SaleHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120, verbose_name='адрес')),
                ('sold', models.BooleanField(default=False, verbose_name='продано')),
                ('number_rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='salehouse.numberofrooms')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house', to='salehouse.roomtype')),
            ],
            options={
                'verbose_name': 'жилье',
                'verbose_name_plural': 'жилье',
            },
        ),
    ]
