# Generated by Django 4.0.6 on 2023-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
