# Generated by Django 4.0.6 on 2023-05-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_newsitem_created_at_newsitem_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('code', models.CharField(max_length=64, verbose_name='код')),
            ],
            options={
                'verbose_name': 'тип новостей',
                'verbose_name_plural': 'типы новостей',
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.newsitem'),
        ),
    ]
