# Generated by Django 4.0.6 on 2023-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_newstype_newsitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('code', models.CharField(max_length=64, verbose_name='код')),
            ],
            options={
                'verbose_name': 'источник новости',
                'verbose_name_plural': 'ичточники новостей',
            },
        ),
    ]
