# Generated by Django 4.0.6 on 2023-05-04 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название магазина')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товар',
                'ordering': ['name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='сумма заказа')),
                ('products', models.ManyToManyField(related_name='orders', to='app_market.product', verbose_name='наименования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='ItemPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='кол-во')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_market.market', verbose_name='в магазине')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_market.product', verbose_name='наименование товара')),
            ],
            options={
                'verbose_name': 'позиция товара',
                'verbose_name_plural': 'позиции товаров',
            },
        ),
    ]
