# Generated by Django 4.0.6 on 2023-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, related_name='orders', to='app_market.product', verbose_name='наименования'),
        ),
    ]
