# Generated by Django 4.0.6 on 2023-05-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
    ]
